### ISSUE TITLE
Starting the bot + Instagram Accounts

### ISSUE THREAD

**Issue by retryoos** [notmonkee/Discord-Instagram-Poster#4]
I am very confused you have a txt file for ids where you have already some Instagram usernames and then in README.md you say to "Replace each line in `config.json` in a text editor with the accounts you wish to monitor." I don't understand because I have everything set up and when I run bot.js I get this error: "image" and when I run node bot.js I get this: "internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'data-store'
Require stack:
- C:\Users\user
![Screenshot_1](https://user-images.githubusercontent.com/50914907/64926549-4fff1a80-d807-11e9-82a7-b4c8c7ebdcf7.png)
\Desktop\Instagram Monitor\Discord-Instagram-Monitor-master\bot.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:681:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:16:16)[39m
    at Object.<anonymous> (C:\Users\user\Desktop\Instagram Monitor\Discord-Instagram-Monitor-master\bot.js:3:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:774:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:641:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\user\\Desktop\\Instagram '[39m +
      [32m'Monitor\\Discord-Instagram-Monitor-master\\bot.js'[39m
  ]
}"

**Comment by hxsseeb** [comment]
npm install data-store
